### ISSUE TITLE
Errors in code 

### ISSUE THREAD

**Issue by bartoszpankratz** [tolcz/ABCDeGraphGenerator.jl#1]
@tolcz @bkamins

Hi, 

Sorry for late response, but I was trying to replicate errors described in https://github.com/bkamins/ABCDGraphGenerator.jl/issues/8#issue-940612333 and https://github.com/bkamins/ABCDGraphGenerator.jl/issues/9#issue-940620338. It took me a while, I was unable to get the errors with a config file, so I tried to debug my code and so on. At the end of the day I run a code in a loop and got both errors almost immidiately. I believe that they are caused by the way how the random numbers are used in a parallelized code - there must be some place which is prone to some weird combination of randomly generated variables. Probably both errors are generated by the same lines of code.

Regarding the error described here:  https://github.com/bkamins/ABCDGraphGenerator.jl/issues/8#issue-940612333  I used the same config file as I described previously (I also attached it with a script and logfile: [assertion_error.zip](https://github.com/tolcz/ABCDeGraphGenerator.jl/files/6933512/assertion_error.zip)), this is a stacktrace:

```julia
ERROR: LoadError: AssertionError: 2 * length(global_edges) == length(stubs)
Stacktrace:
 [1] config_model(clusters::Vector{Int32}, params::ABCDeGraphGenerator.ABCDParams)
   @ ABCDeGraphGenerator ~/.julia/packages/ABCDeGraphGenerator/57M97/src/graph_sampler.jl:389
 [2] gen_graph(params::ABCDeGraphGenerator.ABCDParams)
   @ ABCDeGraphGenerator ~/.julia/packages/ABCDeGraphGenerator/57M97/src/graph_sampler.jl:404
 [3] top-level scope
   @ ~/code_err.jl:34
in expression starting at /root/code_err.jl:32
```
I've got this error with the newest version of the package, 0.2.1.

Files to replicate the second error - https://github.com/bkamins/ABCDGraphGenerator.jl/issues/9#issue-940620338 are avalaible here:  [CFG_parallel_2_error.zip](https://github.com/tolcz/ABCDeGraphGenerator.jl/files/6933538/CFG_parallel_2_error.zip) and the stacktrace looks like that: 

```julia
ERROR: LoadError: TaskFailedException
Stacktrace:
 [1] wait
   @ ./task.jl:322 [inlined]
 [2] threading_run(func::Function)
   @ Base.Threads ./threadingconstructs.jl:34
 [3] macro expansion
   @ ./threadingconstructs.jl:93 [inlined]
 [4] config_model(clusters::Vector{Int32}, params::ABCDeGraphGenerator2.ABCDeParams)
   @ ABCDeGraphGenerator2 ~/.julia/packages/ABCDeGraphGenerator2/2iQog/src/graph_sampler.jl:214
 [5] gen_graph(params::ABCDeGraphGenerator2.ABCDeParams)
   @ ABCDeGraphGenerator2 ~/.julia/packages/ABCDeGraphGenerator2/2iQog/src/graph_sampler.jl:393
 [6] top-level scope
   @ ~/code_err2.jl:34

    nested task error: InvalidStateException("Channel is closed.", :closed)
    Stacktrace:
     [1] check_channel_state
       @ ./channels.jl:170 [inlined]
     [2] take_buffered(c::Channel{Int64})
       @ Base ./channels.jl:388
     [3] take!
       @ ./channels.jl:383 [inlined]
     [4] macro expansion
       @ ~/.julia/packages/ABCDeGraphGenerator2/2iQog/src/graph_sampler.jl:219 [inlined]
     [5] (::ABCDeGraphGenerator2.var"#156#threadsfor_fun#33"{Channel{Int64}, Vector{Int32}, Vector{Int32}, Vector{Tuple{Int32, Int32}}, Set{Tuple{Int32, Int32}}, ReentrantLock, Vector{Int32}, Vector{Set{Tuple{Int32, Int32}}}, Vector{Vector{Int32}}, Vector{Int32}, UnitRange{Int64}})(onethread::Bool)
       @ ABCDeGraphGenerator2 ./threadingconstructs.jl:81
     [6] (::ABCDeGraphGenerator2.var"#156#threadsfor_fun#33"{Channel{Int64}, Vector{Int32}, Vector{Int32}, Vector{Tuple{Int32, Int32}}, Set{Tuple{Int32, Int32}}, ReentrantLock, Vector{Int32}, Vector{Set{Tuple{Int32, Int32}}}, Vector{Vector{Int32}}, Vector{Int32}, UnitRange{Int64}})()
       @ ABCDeGraphGenerator2 ./threadingconstructs.jl:48
in expression starting at /root/code_err2.jl:32
```

This error is often occuring in the alternative version of code (branch CFG_parallel_2), but I was able to also  catch it in a newest release of the main package (version 0.2.1) . Sadly it occurs only once and then, in twenty-something trials, I wasn't able to replicate it.

**Comment by tlcz** [comment]
@bartoszpankratz thank you for testing the package and for the detailed description of the issues. I fixed issue #1.1 with commit [f462e8e](https://github.com/tolcz/ABCDeGraphGenerator.jl/commit/f462e8e29bd586ea5feae67555a31fc7d5c1a508) and issue #1.2 with commit [8a0255f](https://github.com/tolcz/ABCDeGraphGenerator.jl/commit/8a0255fb1b72d67ca856fee28e7cd62d1a3989e1). Could you please pull the changes and confirm whether the issues disappeared?

**Comment by tlcz** [comment]
@bartoszpankratz please make sure you only use branch __master__ for testing. Also if you have any other errors to report could you please submit them one by one as separate 'Issues'? Many thanks!

**Comment by tlcz** [comment]
@bartoszpankratz I close this issue as both errors reported has been fixed. You may reopen if you object.
